"""Direct PyTorch equivalent of HHZ ``sim_T1T2_10HB_bssfp.m``.

This module deliberately implements the two-state HHZ bSSFP recurrence only;
it neither contains nor calls an EPG model.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import torch
from torch import nn


@dataclass(frozen=True)
class TradProtocol:
    """HHZ v1 sequence values, with TR/VPS supplied from DICOM metadata."""

    tr_ms: float
    vps: int
    fa_deg: tuple[float, float, float] = (45.0, 45.0, 45.0)
    ti_ms: tuple[float, float] = (50.0, 150.0)
    t2prep_ms: tuple[float, float, float] = (35.0, 45.0, 55.0)
    n_ramp_up: int = 10

    def validate(self) -> None:
        if self.tr_ms <= 0 or self.vps < 16 or self.n_ramp_up != 10:
            raise ValueError("HHZ protocol requires positive TR, VPS >= 16, and n_ramp_up == 10.")
        if len(self.fa_deg) != 3 or len(self.ti_ms) != 2 or len(self.t2prep_ms) != 3:
            raise ValueError("HHZ protocol requires FA[3], TI[2], and T2prep[3].")
        if tuple(float(x) for x in self.fa_deg) != (45.0, 45.0, 45.0):
            raise ValueError("v1 HHZ protocol requires FA=[45,45,45] degrees.")
        if tuple(float(x) for x in self.ti_ms) != (50.0, 150.0):
            raise ValueError("v1 uses HHZ TI=[50,150] ms; DYZ TI=[10,100] is not permitted.")
        if tuple(float(x) for x in self.t2prep_ms) != (35.0, 45.0, 55.0):
            raise ValueError("v1 HHZ protocol requires T2prep=[35,45,55] ms.")


class TradSignalSimulator(nn.Module):
    """Tensorized-batch, direct 10-heartbeat HHZ bSSFP simulator."""

    def __init__(self) -> None:
        super().__init__()

    @staticmethod
    def _as_tensor(value: torch.Tensor | Sequence[float] | float, reference: torch.Tensor) -> torch.Tensor:
        return torch.as_tensor(value, dtype=reference.dtype, device=reference.device)

    @staticmethod
    def _matlab_round_positive(value: float) -> int:
        """Matlab ``round`` for the positive central-window expression."""

        return int(torch.floor(torch.tensor(value) + 0.5).item())

    def forward(
        self,
        t1_ms: torch.Tensor,
        t2_ms: torch.Tensor,
        b1: torch.Tensor,
        timing9_ms: torch.Tensor,
        protocol: TradProtocol,
        normalize: bool = True,
    ) -> torch.Tensor:
        """Return raw or L2-normalized 10-HB fingerprints.

        ``timing9_ms`` is ``Duration_befor_Acq[1:]``.  The first HHZ duration
        is exactly zero, as generated by `compute_duration_before_acq`.
        """

        protocol.validate()
        if t1_ms.shape != t2_ms.shape or t1_ms.shape != b1.shape:
            raise ValueError("t1_ms, t2_ms, and b1 must have identical shapes.")
        if t1_ms.ndim == 0:
            raise ValueError("Scalar tissue inputs are unsupported; provide a batch-shaped tensor.")
        if timing9_ms.shape[-1] != 9:
            raise ValueError(f"timing9_ms must end in 9 values, got {tuple(timing9_ms.shape)}.")
        if timing9_ms.shape[:-1] != t1_ms.shape:
            raise ValueError("timing9_ms batch dimensions must match tissue inputs.")
        if not all(torch.is_floating_point(t) for t in (t1_ms, t2_ms, b1, timing9_ms)):
            raise TypeError("Simulator inputs must be floating tensors.")
        if not (torch.isfinite(t1_ms).all() and torch.isfinite(t2_ms).all() and torch.isfinite(b1).all() and torch.isfinite(timing9_ms).all()):
            raise ValueError("Simulator inputs must be finite.")
        if torch.any(t1_ms <= 0) or torch.any(t2_ms <= 0):
            raise ValueError("T1 and T2 must be positive.")

        prefix = t1_ms.shape
        flat_t1, flat_t2, flat_b1 = (item.reshape(-1) for item in (t1_ms, t2_ms, b1))
        durations = torch.cat(
            (torch.zeros((flat_t1.numel(), 1), dtype=t1_ms.dtype, device=t1_ms.device), timing9_ms.reshape(-1, 9)),
            dim=1,
        )
        fa = self._as_tensor(protocol.fa_deg, t1_ms)
        ti = self._as_tensor(protocol.ti_ms, t1_ms)
        t2prep = self._as_tensor(protocol.t2prep_ms, t1_ms)
        # MATLAB 1-indexed start: round(npulse/2 - 15/2), inclusive 16 points.
        centre_start_1based = self._matlab_round_positive(protocol.vps / 2.0 - 15.0 / 2.0)
        centre_start_0based = centre_start_1based - 1
        if centre_start_0based < 0 or centre_start_0based + 16 > protocol.vps:
            raise ValueError("VPS does not contain HHZ's required central 16-readout window.")

        e1 = torch.exp(-float(protocol.tr_ms) / flat_t1)
        e2 = torch.exp(-float(protocol.tr_ms) / flat_t2)
        mz = torch.ones_like(flat_t1)  # HHZ: Mz=1, M0=1
        signals: list[torch.Tensor] = []
        for heartbeat in range(10):
            flip_deg = fa[0] if heartbeat < 4 else fa[1] if heartbeat < 7 else fa[2]
            flip_rad = torch.deg2rad(flip_deg * flat_b1)
            duration = durations[:, heartbeat]
            mz = 1.0 + (mz - 1.0) * torch.exp(-duration / flat_t1)
            if heartbeat in (0, 4):
                inversion_delay = ti[0] if heartbeat == 0 else ti[1]
                mz = -mz  # perfect inversion pulse
                mz = 1.0 + (mz - 1.0) * torch.exp(-inversion_delay / flat_t1)
            elif heartbeat >= 7:
                mz = mz * torch.exp(-t2prep[heartbeat - 7] / flat_t2)

            mxy = torch.zeros_like(mz)
            direction = 1.0
            for ramp_idx in range(protocol.n_ramp_up):
                alpha = flip_rad * ((ramp_idx + 1) / protocol.n_ramp_up) * direction
                c, s = torch.cos(alpha), torch.sin(alpha)
                mxy, mz = c * mxy - s * mz, s * mxy + c * mz
                mxy, mz = mxy * e2, 1.0 + (mz - 1.0) * e1
                direction = -direction

            central_samples: list[torch.Tensor] = []
            for pulse_idx in range(protocol.vps):
                alpha = flip_rad * direction
                c, s = torch.cos(alpha), torch.sin(alpha)
                mxy, mz = c * mxy - s * mz, s * mxy + c * mz
                if centre_start_0based <= pulse_idx < centre_start_0based + 16:
                    central_samples.append(mxy.abs())
                mxy, mz = mxy * e2, 1.0 + (mz - 1.0) * e1
                direction = -direction
            signals.append(torch.stack(central_samples, dim=1).mean(dim=1))

        raw = torch.stack(signals, dim=1).reshape(*prefix, 10)
        if normalize:
            return raw / torch.linalg.vector_norm(raw, dim=-1, keepdim=True).clamp_min(torch.finfo(raw.dtype).eps)
        return raw
